---
- name: Ensure the SSL directories exist
  file:
    path: '{{ item|dirname }}'
    state: directory
  become: true
  with_items:
    - '{{ dci_import_keys_sslclientcert }}'
    - '{{ dci_import_keys_sslclientkey }}'

- name: Retrieve remoteci key and certificate from DCI
  dci_keys:
    remoteci_id: '{{ dci_import_keys_remoteci_id }}'
  register: keys

- name: Create the certificate file
  copy:
    content: '{{ keys.cert }}'
    dest: '{{ dci_import_keys_sslclientcert }}'
  when: keys.cert is defined
  become: true

- name: Create the private key file
  copy:
    content: '{{ keys.key }}'
    dest: '{{ dci_import_keys_sslclientkey }}'
    mode: 0600
  when: keys.key is defined
  become: true
